package com.hospital.management.system.enums;

public enum Specialty {
    INTERNAL_MEDICINE,
    FAMILY_MEDICINE,
    PEDIATRICS,
    OBSTETRICS_GYNECOLOGY,
    GENERAL_SURGERY,
    ORTHOPEDIC_SURGERY,
    CARDIOTHORACIC_SURGERY,
    NEUROSURGERY,
    UROLOGY,
    CARDIOLOGY,
    DERMATOLOGY,
    OTOLARYNGOLOGY,
    OPHTHALMOLOGY,
    PULMONOLOGY,
    ONCOLOGY,
    NEUROLOGY,
    EMERGENCY_MEDICINE,
    ANESTHESIOLOGY,
    PSYCHIATRY,
    PHYSICAL_MEDICINE_REHABILITATION,
    BARIATRIC_MEDICINE,
    PSYCHOSOMATIC_MEDICINE
}
